default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: my_app_development

test:
  <<: *default
  database: my_app_test

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV['SUPABASE_DB_NAME'] %>
  username: <%= ENV['SUPABASE_DB_USER'] %>
  password: <%= ENV['SUPABASE_DB_PASSWORD'] %>
  host: <%= ENV['SUPABASE_DB_HOST'] %>
  port: 6543
