default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: storage/development.sqlite3

test:
  <<: *default
  adapter: sqlite3
  database: storage/test.sqlite3

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['SUPABASE_DB_NAME'] %>
  username: <%= ENV['SUPABASE_DB_USER'] %>
  password: <%= ENV['SUPABASE_DB_PASSWORD'] %>
  host: <%= ENV['SUPABASE_DB_HOST'] %>
  port: 6543
